### ISSUE TITLE
【Processing】黒も透過カラーへ

### ISSUE THREAD

**Issue by soichiro-imamura** [036base/Processing#16]
真っ黒も透過カラーへ追加して欲しい
タイトルとか注意書きとか入れたいから！

**Comment by masahiro-kawada** [comment]
あと透過対象は左上４pxだけど、四隅１pxに変える？

**Comment by soichiro-imamura** [comment]
そうだね！四隅1pxで！

**Comment by soichiro-imamura** [comment]
動きまへん(;^ω^)


java.lang.NoClassDefFoundError: com/jogamp/opengl/GLCapabilitiesImmutable
	at processing.opengl.PGraphicsOpenGL.createPGL(PGraphicsOpenGL.java:705)
	at processing.opengl.PGraphicsOpenGL.<init>(PGraphicsOpenGL.java:569)
	at processing.opengl.PGraphics2D.<init>(PGraphics2D.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at processing.core.PApplet.makeGraphics(PApplet.java:2227)
	at processing.core.PApplet.createPrimaryGraphics(PApplet.java:2306)
	at processing.core.PApplet.initSurface(PApplet.java:10584)
	at processing.core.PApplet.runSketch(PApplet.java:10523)
	at processing.core.PApplet.main(PApplet.java:10279)
	at processing.core.PApplet.main(PApplet.java:10261)
	at com.awesomebase.processing.MainSketch.main(MainSketch.java:77)
Caused by: java.lang.ClassNotFoundException: com.jogamp.opengl.GLCapabilitiesImmutable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
java.lang.RuntimeException: com/jogamp/opengl/GLCapabilitiesImmutable
	at processing.core.PApplet.makeGraphics(PApplet.java:2260)
	at processing.core.PApplet.createPrimaryGraphics(PApplet.java:2306)
	at processing.core.PApplet.initSurface(PApplet.java:10584)
	at processing.core.PApplet.runSketch(PApplet.java:10523)
	at processing.core.PApplet.main(PApplet.java:10279)
	at processing.core.PApplet.main(PApplet.java:10261)
	at com.awesomebase.processing.MainSketch.main(MainSketch.java:77)

**Comment by masahiro-kawada** [comment]
ごめん。参照ライブラリー漏れかなーコミットしました。

**Comment by soichiro-imamura** [comment]
ありがとー
お昼確認しまーす！

**Comment by soichiro-imamura** [comment]
なんかインストールが必要？

java.lang.RuntimeException: Framebuffer objects are not supported by this hardware (or driver) Read http://wiki.processing.org/w/OpenGL_Issues for help.
	at processing.opengl.PJOGL.init(PJOGL.java:428)
	at processing.opengl.PSurfaceJOGL$DrawListener.init(PSurfaceJOGL.java:930)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667)
	at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:431)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by masahiro-kawada** [comment]
settings()のP2Dってパラメータ削除して試してみて。

**Comment by masahiro-kawada** [comment]
P2DをFX2Dってして動くかな？
FX2Dの方がスムーズに動いたりする？
どっちもエラーなら指定なしに修正します。

**Comment by soichiro-imamura** [comment]
今は確認できないや。。
settings()ってどこにあるの？

**Comment by masahiro-kawada** [comment]
了解です。とりあえず指定無しでコミットしとく。
MainSketch.javaにメソッドがあるから、あとでFX2D指定を試してみて。
----------------------------------------------------------------------------
P2D:OpenGL互換のグラフィックスハードウェアを利用した2Dグラフィックスです
P3D:OpenGL互換のグラフィックスハードウェアを利用した3Dグラフィックスです。
PDF：2次元座標の画像を直接PDFに書き込むように指定します。
JAVA2D：2Dグラフィックスです。デフォルトのレンダラーです。
FX2D：2Dグラフィックスです。JAVA2Dを高速化したレンダラーです。
----------------------------------------------------------------------------
ごめん、P2Dがデフォルトかと思ってた。。。

**Comment by masahiro-kawada** [comment]
了解です。とりあえず指定無しでコミットしとく。

MainSketch.javaにメソッドがあるから、あとでFX2D指定を試してみて。
P2D:OpenGL互換のグラフィックスハードウェアを利用した2Dグラフィックスです
P3D:OpenGL互換のグラフィックスハードウェアを利用した3Dグラフィックスです。
PDF：2次元座標の画像を直接PDFに書き込むように指定します。
JAVA2D：2Dグラフィックスです。デフォルトのレンダラーです。
FX2D：2Dグラフィックスです。JAVA2Dを高速化したレンダラーです。

ごめん、P2Dがデフォルトかと思ってた。。。

**Comment by soichiro-imamura** [comment]
了解です。

そっちだとFX2Dで動いたの？

**Comment by masahiro-kawada** [comment]
FX2Dでも動いたよ。こっちの方がスムーズに動いてる気がする。
確認はしてないけど、もしかしたらメモリを多く食うのかもしれないけど。

**Comment by masahiro-kawada** [comment]
てか３Dを扱うには、P3Dしかないっぽいんだけど、P2Dがダメってことは今村君のPCは３Dは動かせないかもしれないね。。。(^^;)

**Comment by soichiro-imamura** [comment]
こっちでやると、
FX2Dはカクカク感がすごいね！
指定なしの速度５が一番まとも！
早くなったり遅くなったりしなくなった。。。（感じれなくなった。。）
ちょっと前はまだスムーズに動いてた気がするんだけど。。。

**Comment by soichiro-imamura** [comment]
↑
Fullにするとだね。画面小さいとサクサク動く！
直したんじゃなかったっけ。。。

**Comment by soichiro-imamura** [comment]
同じ現象かな？
http://skomo.o.oo7.jp/f48/hp48_51.htm

**Comment by masahiro-kawada** [comment]
P2Dでエラーになるのは↑と同じかもね。ドライバーの問題だと思う。

特に動きに関しては修正はしてないはずなんだけどな。
Fullだと重たくなるのかな。。。

**Comment by masahiro-kawada** [comment]
この辺の設定で処理は早くなるかも。
http://www.musashinodenpa.com/p5/index.php?pos=976
http://www.musashinodenpa.com/p5/index.php?pos=208

**Comment by soichiro-imamura** [comment]
Color.BLACK.getRGB()の判定じゃ効かないね。
たぶんアプリで撮影したときBLACKじゃなくなるんだと思う。
濃灰～黒までみたいな範囲でやらないといけないと思う。

**Comment by soichiro-imamura** [comment]
→黒はやっぱいいや！
　撮影側でなんとかする。
　黒で塗ってる子もいたから、透明になってもｗ
　ごめん！

**Comment by masahiro-kawada** [comment]
じゃ透過するのは白＋画像四隅１ｐｘにしときます。
