### ISSUE TITLE
【エラー】ヌルポ

### ISSUE THREAD

**Issue by soichiro-imamura** [036base/Processing#26]
2017-06-12 21:28:55.073 [ INFO  ] com.awesomebase.processing.MainSketch3D - com.awesomebase.processing.MainSketch3D start... 
2017-06-12 21:28:55.142 [ INFO  ] com.awesomebase.processing.MainSketch3D - Settings... 
2017-06-12 21:28:55.143 [ INFO  ] com.awesomebase.processing.MainSketch3D - --- System Settings --------------------------------------- 
2017-06-12 21:28:55.143 [ INFO  ] com.awesomebase.processing.MainSketch3D - full_screen             : 1 
2017-06-12 21:28:55.143 [ INFO  ] com.awesomebase.processing.MainSketch3D - display_no              : 2 
2017-06-12 21:28:55.144 [ INFO  ] com.awesomebase.processing.MainSketch3D - screen_size             : 600,400 
2017-06-12 21:28:55.144 [ INFO  ] com.awesomebase.processing.MainSketch3D - dir_animated_image      : C:\Processing\image\animation 
2017-06-12 21:28:55.144 [ INFO  ] com.awesomebase.processing.MainSketch3D - dir_monitoring_interval : 10000 
2017-06-12 21:28:55.144 [ INFO  ] com.awesomebase.processing.MainSketch3D - background_mode         : 1 
2017-06-12 21:28:55.144 [ INFO  ] com.awesomebase.processing.MainSketch3D - file_background_image   : C:\Processing\image\background\grassland.png 
2017-06-12 21:28:55.144 [ INFO  ] com.awesomebase.processing.MainSketch3D - file_background_movie   : C:\Processing\movie\Landscape - 1758.mp4 
2017-06-12 21:28:55.144 [ INFO  ] com.awesomebase.processing.MainSketch3D - max_image_count         : 50 
2017-06-12 21:28:55.144 [ INFO  ] com.awesomebase.processing.MainSketch3D - default_image_width     : 128 
2017-06-12 21:28:55.144 [ INFO  ] com.awesomebase.processing.MainSketch3D - default_animation_speed : 1.0 
2017-06-12 21:28:55.144 [ INFO  ] com.awesomebase.processing.MainSketch3D - ----------------------------------------------------------- 
2017-06-12 21:28:55.164 [ INFO  ] com.awesomebase.processing.MainSketch3D - File monitoring started... 
2017-06-12 21:28:56.712 [ INFO  ] com.awesomebase.processing.MainSketch3D - Setup... 
2017-06-12 21:28:58.203 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611104602990.png 
2017-06-12 21:28:58.347 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611105018222.png 
2017-06-12 21:28:58.426 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611105118144.png 
2017-06-12 21:28:58.604 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611105220407.png 
2017-06-12 21:28:58.672 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611105420122.png 
2017-06-12 21:28:58.723 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611105546538.png 
2017-06-12 21:28:58.796 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611105645742.png 
2017-06-12 21:28:58.891 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611105824602.png 
2017-06-12 21:28:58.945 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611105825933.png 
2017-06-12 21:28:58.997 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611110032328.png 
2017-06-12 21:28:59.110 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611110900798.png 
2017-06-12 21:28:59.218 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611111257081.png 
2017-06-12 21:28:59.285 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611113212314.png 
2017-06-12 21:28:59.337 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611114457258.png 
2017-06-12 21:28:59.463 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611114457999.png 
2017-06-12 21:28:59.601 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611115355576.png 
2017-06-12 21:28:59.720 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611115518984.png 
2017-06-12 21:28:59.776 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611115913906.png 
2017-06-12 21:28:59.868 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611120322023.png 
2017-06-12 21:28:59.967 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611121052087.png 
2017-06-12 21:29:00.123 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611121122821.png 
2017-06-12 21:29:00.268 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611121610737.png 
2017-06-12 21:29:00.327 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611121932953.png 
2017-06-12 21:29:00.375 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611121934015.png 
2017-06-12 21:29:00.447 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611122002470.png 
2017-06-12 21:29:00.501 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611122706570.png 
2017-06-12 21:29:00.628 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611123119448.png 
2017-06-12 21:29:00.719 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611123119951.png 
2017-06-12 21:29:00.785 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611123248253.png 
2017-06-12 21:29:00.932 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611123425944.png 
2017-06-12 21:29:00.995 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611123724269.png 
2017-06-12 21:29:01.094 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611123824476.png 
2017-06-12 21:29:01.181 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611124852276.png 
2017-06-12 21:29:01.236 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611125457349.png 
2017-06-12 21:29:01.357 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611130238419.png 
2017-06-12 21:29:01.407 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611130309278.png 
2017-06-12 21:29:01.471 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611130831357.png 
2017-06-12 21:29:01.567 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611130901424.png 
2017-06-12 21:29:01.708 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611131137196.png 
2017-06-12 21:29:01.828 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611132014645.png 
2017-06-12 21:29:01.988 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611133931400.png 
2017-06-12 21:29:02.096 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611134924118.png 
2017-06-12 21:29:02.209 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611135057786.png 
2017-06-12 21:29:02.328 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611135128418.png 
2017-06-12 21:29:02.437 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611135252433.png 
2017-06-12 21:29:02.569 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611142921405.png 
2017-06-12 21:29:02.722 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611142921777.png 
2017-06-12 21:29:02.858 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611143331588.png 
2017-06-12 21:29:02.940 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611143332034.png 
2017-06-12 21:29:02.989 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611143502635.png 
2017-06-12 21:29:03.125 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611144241636.png 
2017-06-12 21:29:03.226 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611144242260.png 
2017-06-12 21:29:03.306 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611144242467.png 
2017-06-12 21:29:03.419 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611144242912.png 
2017-06-12 21:29:03.519 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611144601560.png 
2017-06-12 21:29:03.632 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611144702380.png 
2017-06-12 21:29:03.680 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611144834921.png 
2017-06-12 21:29:03.727 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611144835275.png 
2017-06-12 21:29:03.778 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611145841496.png 
2017-06-12 21:29:03.840 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611150648357.png 
2017-06-12 21:29:03.973 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611150648687.png 
2017-06-12 21:29:04.023 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611150748309.png 
2017-06-12 21:29:04.082 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611151152314.png 
2017-06-12 21:29:04.233 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611151253763.png 
2017-06-12 21:29:04.436 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611152000772.png 
2017-06-12 21:29:04.529 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611152756727.png 
2017-06-12 21:29:04.582 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611154044004.png 
2017-06-12 21:29:04.632 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170611155133483.png 
java.lang.NullPointerException
	at processing.opengl.Texture.copyBufferFromSource(Texture.java:825)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.video.Movie.read(Unknown Source)
	at com.awesomebase.processing.MainSketch3D.movieEvent(MainSketch3D.java:268)
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.video.Movie.fireMovieEvent(Unknown Source)
	at processing.video.Movie.invokeEvent(Unknown Source)
	at processing.video.Movie$1.bufferFrame(Unknown Source)
	at org.gstreamer.elements.BufferDataAppSink$AppSinkNewBufferListener.newBuffer(BufferDataAppSink.java:163)
	at org.gstreamer.elements.AppSink$2.callback(AppSink.java:184)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:485)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:515)
java.lang.NullPointerException
	at processing.opengl.Texture.copyBufferFromSource(Texture.java:825)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.video.Movie.read(Unknown Source)
	at com.awesomebase.processing.MainSketch3D.movieEvent(MainSketch3D.java:268)
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.video.Movie.fireMovieEvent(Unknown Source)
	at processing.video.Movie.invokeEvent(Unknown Source)
	at processing.video.Movie$1.bufferFrame(Unknown Source)
	at org.gstreamer.elements.BufferDataAppSink$AppSinkNewBufferListener.newBuffer(BufferDataAppSink.java:163)
	at org.gstreamer.elements.AppSink$2.callback(AppSink.java:184)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:485)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:515)
2017-06-12 21:31:15.401 [ INFO  ] com.awesomebase.processing.MainSketch3D - Create image 20170612213114622.png 
2017-06-12 21:39:24.214 [ INFO  ] com.awesomebase.processing.MainSketch3D - Exit... 
2017-06-12 21:39:24.214 [ INFO  ] com.awesomebase.processing.MainSketch3D - Exit... 
2017-06-12 21:39:24.215 [ INFO  ] com.awesomebase.processing.MainSketch3D - Dispose...

**Comment by soichiro-imamura** [comment]
そういえばエラー出てた
落ちるわけじゃないんだけど
これでメモリリークも起こした

**Comment by masahiro-kawada** [comment]
↑このエラーとは直接関係はないと思うけど、
管理画面からの起動で挙動がおかしいかもしれない。

起動方法をいろいろ試してはいるけど、停止ができない。
他に
画像取り込み時のコンソール表示でもエラーが出ることがある。
落ちるわけではないけど、なんかコンソールにエラー出ることがある。

検証、調査を継続します。

**Comment by soichiro-imamura** [comment]
お願いしまーす
